School.create(name: 'Beattie', level: 'Elementary')
School.create(name: 'Hazel G. Scott', level: 'Middle School')
School.create(name: 'Irving', level: 'Junior High')
School.create(name: 'Southwest', level: 'High School')
School.create(name: 'Southeast', level: 'High School')
School.create(name: 'BYU', level: 'University')
School.create(name: 'UNL', level: 'University')
School.create(name: 'Columbia', level: 'University')
School.create(name: 'New Mexico Tech', level: 'University')
School.create(name: 'Duke', level: 'University')
School.create(name: 'Stanford', level: 'University')

